[theme]
base = "light"
primaryColor = "#0E7C66"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6F8"
textColor = "#16191D"
font = "sans serif"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true
